// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT conversation_id
FROM direct_conversations
WHERE user_one_id = $1
AND user_two_id = $2
`

type FindDirectConversationParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConvUsers = `-- name: GetConvUsers :many
SELECT user_one_id AS user_id
FROM direct_conversations dc
WHERE dc.conversation_id = $1

UNION ALL

SELECT user_two_id AS user_id
FROM direct_conversations dc
WHERE dc.conversation_id = $1

UNION ALL

SELECT user_id
FROM group_members
WHERE group_id = $1
`

func (q *Queries) GetConvUsers(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConvUsers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT
    c.id AS conversation_id,

    CASE
        WHEN dc.conversation_id IS NOT NULL THEN 'direct'
        ELSE 'group'
    END AS conversation_type,

    -- direct user
    u.id AS user_id,
    u.username,
    u.display_name,
    u.avatar_key,
    u.last_seen,

    -- group
    g.name AS group_name,
    g.avatar_key AS group_avatar_key,

    -- last message
    c.last_message_id,
    c.last_message_type,
    c.last_message_text,
    c.last_message_created_at,

    c.updated_at

FROM conversations c

LEFT JOIN direct_conversations dc
    ON dc.conversation_id = c.id

LEFT JOIN users u
    ON u.id = CASE
        WHEN dc.user_one_id = $1 THEN dc.user_two_id
        ELSE dc.user_one_id
    END

LEFT JOIN groups g
    ON g.conversation_id = c.id

LEFT JOIN group_members gm
    ON gm.group_id = c.id
    AND gm.user_id = $1

WHERE
    c.id = $2
    AND (
        dc.user_one_id = $1
        OR dc.user_two_id = $1
        OR gm.user_id IS NOT NULL
    )
`

type GetConversationByIDParams struct {
	UserID         uuid.UUID
	ConversationID uuid.UUID
}

type GetConversationByIDRow struct {
	ConversationID       uuid.UUID
	ConversationType     string
	UserID               pgtype.UUID
	Username             pgtype.Text
	DisplayName          pgtype.Text
	AvatarKey            pgtype.Text
	LastSeen             pgtype.Timestamptz
	GroupName            pgtype.Text
	GroupAvatarKey       pgtype.Text
	LastMessageID        pgtype.Int8
	LastMessageType      NullMessageType
	LastMessageText      pgtype.Text
	LastMessageCreatedAt pgtype.Timestamptz
	UpdatedAt            time.Time
}

func (q *Queries) GetConversationByID(ctx context.Context, arg GetConversationByIDParams) (GetConversationByIDRow, error) {
	row := q.db.QueryRow(ctx, getConversationByID, arg.UserID, arg.ConversationID)
	var i GetConversationByIDRow
	err := row.Scan(
		&i.ConversationID,
		&i.ConversationType,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarKey,
		&i.LastSeen,
		&i.GroupName,
		&i.GroupAvatarKey,
		&i.LastMessageID,
		&i.LastMessageType,
		&i.LastMessageText,
		&i.LastMessageCreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationInfo = `-- name: GetConversationInfo :one
SELECT
    c.id,
    CASE
        WHEN dc.conversation_id IS NOT NULL THEN 'direct'
        ELSE 'group'
    END AS conversation_type,

    u.id AS user_id,
    u.username,
    u.display_name,
    u.avatar_key,
    u.bio,

    g.conversation_id AS group_id,
    g.name AS group_name,
    g.avatar_key AS group_avatar_key,
    g.bio AS group_bio,
    g.invite_code,
    gm.role AS viewer_role,
    (
        SELECT COUNT(*)
        FROM group_members gmc
        WHERE gmc.group_id = g.conversation_id
    ) AS member_count
FROM conversations c
LEFT JOIN direct_conversations dc ON dc.conversation_id = c.id
LEFT JOIN users u ON u.id = CASE
    WHEN dc.user_one_id = $1 THEN dc.user_two_id
    ELSE dc.user_one_id
END
LEFT JOIN groups g ON g.conversation_id = c.id
LEFT JOIN group_members gm
    ON gm.group_id = c.id
    AND gm.user_id = $1
WHERE c.id = $2
`

type GetConversationInfoParams struct {
	UserID         uuid.UUID
	ConversationID uuid.UUID
}

type GetConversationInfoRow struct {
	ID               uuid.UUID
	ConversationType string
	UserID           pgtype.UUID
	Username         pgtype.Text
	DisplayName      pgtype.Text
	AvatarKey        pgtype.Text
	Bio              pgtype.Text
	GroupID          pgtype.UUID
	GroupName        pgtype.Text
	GroupAvatarKey   pgtype.Text
	GroupBio         pgtype.Text
	InviteCode       pgtype.Text
	ViewerRole       NullGroupMemberRole
	MemberCount      int64
}

func (q *Queries) GetConversationInfo(ctx context.Context, arg GetConversationInfoParams) (GetConversationInfoRow, error) {
	row := q.db.QueryRow(ctx, getConversationInfo, arg.UserID, arg.ConversationID)
	var i GetConversationInfoRow
	err := row.Scan(
		&i.ID,
		&i.ConversationType,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Bio,
		&i.GroupID,
		&i.GroupName,
		&i.GroupAvatarKey,
		&i.GroupBio,
		&i.InviteCode,
		&i.ViewerRole,
		&i.MemberCount,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT
    m.message_id,
    m.conversation_id,
    m.sender_id,
    m.type,
    tm.content,
    fm.file_key,
    fm.category,
    fm.content_type,
    fm.size_bytes,
    fm.file_name,
    fm.caption,
    m.created_at,
    m.updated_at
FROM messages m
LEFT JOIN text_messages tm
    ON tm.conversation_id = m.conversation_id
    AND tm.message_id = m.message_id
LEFT JOIN file_messages fm
    ON fm.conversation_id = m.conversation_id
    AND fm.message_id = m.message_id
WHERE m.conversation_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (m.created_at, m.message_id) < (
          $2::timestamptz,
          $3::BIGINT
      )
  )
ORDER BY m.created_at DESC
LIMIT $4
`

type GetConversationMessagesParams struct {
	ConversationID  uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.Int8
	QueryLimit      int32
}

type GetConversationMessagesRow struct {
	MessageID      int64
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Type           MessageType
	Content        pgtype.Text
	FileKey        pgtype.Text
	Category       pgtype.Text
	ContentType    pgtype.Text
	SizeBytes      pgtype.Int8
	FileName       pgtype.Text
	Caption        pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages,
		arg.ConversationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.FileKey,
			&i.Category,
			&i.ContentType,
			&i.SizeBytes,
			&i.FileName,
			&i.Caption,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT conversation_id
FROM direct_conversations
WHERE user_one_id = $1
AND user_two_id = $2
`

type GetDirectConversationParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_key,
    gm.role AS member_role
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND (
    $2::uuid IS NULL
    OR (u.id) > $2::uuid)
ORDER BY u.id
LIMIT $3
`

type GetGroupMembersParams struct {
	ConversationID uuid.UUID
	CursorUserID   uuid.UUID
	CursorLimit    int32
}

type GetGroupMembersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName pgtype.Text
	AvatarKey   pgtype.Text
	MemberRole  GroupMemberRole
}

func (q *Queries) GetGroupMembers(ctx context.Context, arg GetGroupMembersParams) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, arg.ConversationID, arg.CursorUserID, arg.CursorLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT
    c.id AS conversation_id,

    CASE
        WHEN dc.conversation_id IS NOT NULL THEN 'direct'
        ELSE 'group'
    END AS conversation_type,

    -- direct user
    u.id AS user_id,
    u.username,
    u.display_name,
    u.avatar_key,

    -- group
    g.name AS group_name,
    g.avatar_key AS group_avatar_key,

    -- last message
    c.last_message_id,
    c.last_message_type,
    c.last_message_text,
    c.last_message_created_at,

    c.updated_at

FROM conversations c

LEFT JOIN direct_conversations dc
    ON dc.conversation_id = c.id

LEFT JOIN users u
    ON u.id = CASE
        WHEN dc.user_one_id = $1 THEN dc.user_two_id
        ELSE dc.user_one_id
    END

LEFT JOIN groups g
    ON g.conversation_id = c.id

LEFT JOIN group_members gm
    ON gm.group_id = c.id
    AND gm.user_id = $1

WHERE
    (
        dc.user_one_id = $1
        OR dc.user_two_id = $1
        OR gm.user_id IS NOT NULL
    )
    AND (
        $2::timestamptz IS NULL
        OR c.updated_at < $2
        OR (
            c.updated_at = $2
            AND c.id < $3
        )
    )

ORDER BY
    c.updated_at DESC,
    c.id DESC

LIMIT $4
`

type GetUserConversationsParams struct {
	UserID          uuid.UUID
	CursorUpdatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	QueryLimit      int32
}

type GetUserConversationsRow struct {
	ConversationID       uuid.UUID
	ConversationType     string
	UserID               pgtype.UUID
	Username             pgtype.Text
	DisplayName          pgtype.Text
	AvatarKey            pgtype.Text
	GroupName            pgtype.Text
	GroupAvatarKey       pgtype.Text
	LastMessageID        pgtype.Int8
	LastMessageType      NullMessageType
	LastMessageText      pgtype.Text
	LastMessageCreatedAt pgtype.Timestamptz
	UpdatedAt            time.Time
}

func (q *Queries) GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations,
		arg.UserID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationType,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.GroupName,
			&i.GroupAvatarKey,
			&i.LastMessageID,
			&i.LastMessageType,
			&i.LastMessageText,
			&i.LastMessageCreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations(type,message_id_counter)
VALUES ($1,0)
RETURNING id
`

func (q *Queries) InsertConversation(ctx context.Context, conversationType ConversationType) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertConversation, conversationType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertConversationLastMessage = `-- name: InsertConversationLastMessage :exec
UPDATE conversations 
SET updated_at = $1,
    last_message_id = $2,
    last_message_type = $3,
    last_message_text = $4,
    last_message_created_at = $1
WHERE id = $5
`

type InsertConversationLastMessageParams struct {
	CreatedAt      time.Time
	MessageID      pgtype.Int8
	MessageType    NullMessageType
	MessageText    pgtype.Text
	ConversationID uuid.UUID
}

func (q *Queries) InsertConversationLastMessage(ctx context.Context, arg InsertConversationLastMessageParams) error {
	_, err := q.db.Exec(ctx, insertConversationLastMessage,
		arg.CreatedAt,
		arg.MessageID,
		arg.MessageType,
		arg.MessageText,
		arg.ConversationID,
	)
	return err
}

const insertDirectConversation = `-- name: InsertDirectConversation :one
INSERT INTO direct_conversations(
    conversation_id,
    user_one_id,
    user_two_id
)
VALUES(
    $1,
    $2,
    $3
)
RETURNING conversation_id
`

type InsertDirectConversationParams struct {
	ConversationID uuid.UUID
	UserOneID      uuid.UUID
	UserTwoID      uuid.UUID
}

func (q *Queries) InsertDirectConversation(ctx context.Context, arg InsertDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDirectConversation, arg.ConversationID, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
    SELECT 1
    FROM direct_conversations dc
    WHERE dc.conversation_id = $1 AND (dc.user_one_id = $2 OR dc.user_two_id = $2)

    UNION ALL

    SELECT 1
    FROM group_members gm
    WHERE gm.group_id = $1 AND gm.user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateConversationLastMessageContent = `-- name: UpdateConversationLastMessageContent :exec
UPDATE conversations
SET last_message_type = $1,
    last_message_text = $2
WHERE id = $3
  AND last_message_id = $4
`

type UpdateConversationLastMessageContentParams struct {
	MessageType    NullMessageType
	MessageText    pgtype.Text
	ConversationID uuid.UUID
	MessageID      pgtype.Int8
}

func (q *Queries) UpdateConversationLastMessageContent(ctx context.Context, arg UpdateConversationLastMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessageContent,
		arg.MessageType,
		arg.MessageText,
		arg.ConversationID,
		arg.MessageID,
	)
	return err
}
