// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT conversation_id
FROM direct_conversations
WHERE user_one_id = $1
AND user_two_id = $2
`

type FindDirectConversationParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT conversation_id
FROM direct_conversations
WHERE user_one_id = $1
AND user_two_id = $2
`

type GetDirectConversationParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getUserConversations = `-- name: GetUserConversations :many

SELECT
    c.id AS conversation_id,

    CASE
        WHEN dc.conversation_id IS NOT NULL THEN 'direct'
        ELSE 'group'
    END AS conversation_type,

    -- direct user
    u.id AS user_id,
    u.username,
    u.display_name,
    u.avatar_url,

    -- group
    g.name AS group_name,
    g.avatar_url AS group_avatar_url,

    -- last message
    c.last_message_id,
    c.last_message_content,
    c.last_message_created_at,

    c.updated_at

FROM conversations c

LEFT JOIN direct_conversations dc
    ON dc.conversation_id = c.id

LEFT JOIN users u
    ON u.id = CASE
        WHEN dc.user_one_id = $1 THEN dc.user_two_id
        ELSE dc.user_one_id
    END

LEFT JOIN groups g
    ON g.conversation_id = c.id

LEFT JOIN group_members gm
    ON gm.group_id = c.id
    AND gm.user_id = $1

WHERE
    (
        dc.user_one_id = $1
        OR dc.user_two_id = $1
        OR gm.user_id IS NOT NULL
    )
    AND (
        $2::timestamptz IS NULL
        OR c.updated_at < $2
        OR (
            c.updated_at = $2
            AND c.id < $3
        )
    )

ORDER BY
    c.updated_at DESC,
    c.id DESC

LIMIT $4
`

type GetUserConversationsParams struct {
	UserID          uuid.UUID
	CursorUpdatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	QueryLimit      int32
}

type GetUserConversationsRow struct {
	ConversationID       uuid.UUID
	ConversationType     string
	UserID               pgtype.UUID
	Username             pgtype.Text
	DisplayName          pgtype.Text
	AvatarUrl            pgtype.Text
	GroupName            pgtype.Text
	GroupAvatarUrl       pgtype.Text
	LastMessageID        pgtype.UUID
	LastMessageContent   pgtype.Text
	LastMessageCreatedAt pgtype.Timestamptz
	UpdatedAt            time.Time
}

func (q *Queries) GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations,
		arg.UserID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationType,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GroupName,
			&i.GroupAvatarUrl,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations(type)
VALUES ('direct')
RETURNING id
`

func (q *Queries) InsertConversation(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertConversation)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDirectConversation = `-- name: InsertDirectConversation :one
INSERT INTO direct_conversations(
    conversation_id,
    user_one_id,
    user_two_id
)
VALUES(
    $1,
    $2,
    $3
)
RETURNING conversation_id
`

type InsertDirectConversationParams struct {
	ConversationID uuid.UUID
	UserOneID      uuid.UUID
	UserTwoID      uuid.UUID
}

func (q *Queries) InsertDirectConversation(ctx context.Context, arg InsertDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDirectConversation, arg.ConversationID, arg.UserOneID, arg.UserTwoID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}
