// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) AS member_count
FROM group_members
WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var member_count int64
	err := row.Scan(&member_count)
	return member_count, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, groupID)
	return err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT
    g.conversation_id,
    g.name,
    g.avatar_url,
    g.invite_code,
    g.bio,
    g.created_by,
    g.created_at,
    g.updated_at,
    (
        SELECT COUNT(*)
        FROM group_members gm
        WHERE gm.group_id = g.conversation_id
    ) AS member_count
FROM groups g
WHERE g.invite_code = $1
`

type GetGroupByInviteCodeRow struct {
	ConversationID uuid.UUID
	Name           string
	AvatarUrl      pgtype.Text
	InviteCode     pgtype.Text
	Bio            pgtype.Text
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MemberCount    int64
}

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode pgtype.Text) (GetGroupByInviteCodeRow, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i GetGroupByInviteCodeRow
	err := row.Scan(
		&i.ConversationID,
		&i.Name,
		&i.AvatarUrl,
		&i.InviteCode,
		&i.Bio,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberCount,
	)
	return i, err
}

const getGroupMemberRole = `-- name: GetGroupMemberRole :one
SELECT role
FROM group_members
WHERE group_id = $1
  AND user_id = $2
`

type GetGroupMemberRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetGroupMemberRole(ctx context.Context, arg GetGroupMemberRoleParams) (GroupMemberRole, error) {
	row := q.db.QueryRow(ctx, getGroupMemberRole, arg.GroupID, arg.UserID)
	var role GroupMemberRole
	err := row.Scan(&role)
	return role, err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (
    conversation_id,
    name,
    bio,
    invite_code,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    conversation_id,
    name,
    avatar_url,
    invite_code,
    bio,
    created_by,
    created_at,
    updated_at
`

type InsertGroupParams struct {
	ConversationID uuid.UUID
	Name           string
	Bio            pgtype.Text
	InviteCode     pgtype.Text
	CreatedBy      uuid.UUID
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup,
		arg.ConversationID,
		arg.Name,
		arg.Bio,
		arg.InviteCode,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ConversationID,
		&i.Name,
		&i.AvatarUrl,
		&i.InviteCode,
		&i.Bio,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT INTO group_members (
    group_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type InsertGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    GroupMemberRole
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1
  AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
