// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    sender_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING message_id, created_at, updated_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
}

type CreateMessageRow struct {
	MessageID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i CreateMessageRow
	err := row.Scan(&i.MessageID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $1,
    update_at = NOW()
WHERE message_id = $2 and conversation_id = $3 and sender_id = $4
RETURNING updated_at
`

type UpdateMessageParams struct {
	Msgtext        string
	MessageID      int64
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateMessage,
		arg.Msgtext,
		arg.MessageID,
		arg.ConversationID,
		arg.UserID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
