// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationType string

const (
	ConversationTypeGroup  ConversationType = "group"
	ConversationTypeDirect ConversationType = "direct"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType
	Valid            bool // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type GroupMemberRole string

const (
	GroupMemberRoleOwner  GroupMemberRole = "owner"
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole
	Valid           bool // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type MessageType string

const (
	MessageTypeText MessageType = "text"
	MessageTypeFile MessageType = "file"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType
	Valid       bool // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type Conversation struct {
	ID                   uuid.UUID
	Type                 ConversationType
	LastMessageID        pgtype.Int8
	LastMessageType      NullMessageType
	LastMessageText      pgtype.Text
	LastMessageCreatedAt pgtype.Timestamptz
	MessageIDCounter     int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type DirectConversation struct {
	ConversationID uuid.UUID
	UserOneID      uuid.UUID
	UserTwoID      uuid.UUID
	CreatedAt      time.Time
}

type FileMessage struct {
	ConversationID uuid.UUID
	MessageID      int64
	FileKey        string
	Category       string
	ContentType    string
	SizeBytes      int64
	FileName       string
	Caption        string
}

type Group struct {
	ConversationID uuid.UUID
	Name           string
	AvatarKey      pgtype.Text
	InviteCode     pgtype.Text
	Bio            pgtype.Text
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GroupMember struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     GroupMemberRole
	JoinedAt time.Time
}

type Message struct {
	MessageID      int64
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Type           MessageType
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type TextMessage struct {
	ConversationID uuid.UUID
	MessageID      int64
	Content        string
}

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  pgtype.Text
	AvatarKey    pgtype.Text
	Bio          pgtype.Text
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastSeen     pgtype.Timestamptz
}
