// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GroupMemberRole string

const (
	GroupMemberRoleOwner  GroupMemberRole = "owner"
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole
	Valid           bool // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type Conversation struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	LastMessageID        pgtype.UUID
	LastMessageContent   pgtype.Text
	LastMessageCreatedAt pgtype.Timestamptz
}

type DirectConversation struct {
	ConversationID uuid.UUID
	UserOneID      uuid.UUID
	UserTwoID      uuid.UUID
	CreatedAt      time.Time
}

type Group struct {
	ConversationID uuid.UUID
	Name           string
	AvatarUrl      pgtype.Text
	InviteCode     pgtype.Text
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GroupMember struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     GroupMemberRole
	JoinedAt time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  pgtype.Text
	AvatarUrl    pgtype.Text
	Bio          pgtype.Text
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
