// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password_hash
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    username,
    password_hash,
    display_name,
    avatar_key,
    bio,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

type CreateUserRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarKey    pgtype.Text
	Bio          pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    password_hash,
    display_name,
    avatar_key,
    bio,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarKey    pgtype.Text
	Bio          pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    password_hash,
    display_name,
    avatar_key,
    bio,
    created_at,
    updated_at
FROM users
WHERE username = $1
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarKey    pgtype.Text
	Bio          pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    id,
    username,
    display_name,
    avatar_key
FROM users
WHERE username LIKE '%' || $1 || '%'
ORDER BY username
LIMIT 20
`

type SearchUsersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName pgtype.Text
	AvatarKey   pgtype.Text
}

func (q *Queries) SearchUsers(ctx context.Context, query pgtype.Text) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username     = $2,
    display_name = $3,
    avatar_key   = $4,
    bio          = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING
    id,
    username,
    password_hash,
    display_name,
    avatar_key,
    bio,
    created_at,
    updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	Username    string
	DisplayName pgtype.Text
	AvatarKey   pgtype.Text
	Bio         pgtype.Text
}

type UpdateUserRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarKey    pgtype.Text
	Bio          pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarKey,
		arg.Bio,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarKey,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username = $1
)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
